#!/usr/bin/env python3
"""Генерация labels для составного пака juliet_diary (лесная тропа 2)."""

from __future__ import annotations

import json
from pathlib import Path

from combo_schema import AGENT_RULES, SPACER_GUIDANCE, normalize_combos
from item_builder import build_by_tag, build_items

PACK = "juliet_diary_lesnaya_tropa_2_by_TgEmojiBot"

SPARKLE_MIX = ["sparkle_*"]


def _spacer(idx: int) -> dict:
    return {
        "id": f"spacer_{idx}",
        "name": f"Пустой spacer #{idx:03d}",
        "indices": [idx],
        "layout": "spacer",
        "item_type": "spacer",
        "glue": False,
        "max_per_message": 8,
        "complete": True,
        "description": (
            f"Пустой/прозрачный стикер #{idx:03d} — технический отступ, не декор. "
            "Вставляй между combo или по краям, чтобы крупные стикеры не слипались."
        ),
        "description_emoji": "⬜️📐",
        "tags": ["spacer", "отступ", "пустой", "вёрстка"],
        "mood": "neutral",
        "use_when": [
            "отступ между двумя combo",
            "поле по краям grid",
            "зазор вокруг крупной сцены",
        ],
    }


def _sparkle(cid: str, idx: int, name: str, emoji: str, max_per: int = 2) -> dict:
    return {
        "id": cid,
        "name": name,
        "indices": [idx],
        "layout": "solo",
        "glue": False,
        "accent_only": True,
        "max_per_message": max_per,
        "do_not_mix_with": SPARKLE_MIX,
        "description": f"{name} — одиночный акцент, не склеивать с другими бликами в «объект».",
        "description_emoji": emoji,
        "tags": ["блик", "звезда", "акцент", "solo"],
        "mood": "happy",
        "use_when": ["магический акцент", "разделитель"],
    }

# Готовые сборки: id -> метаданные + indices
COMBOS_RAW: list[dict] = [
    {
        "id": "vine_border_top",
        "name": "Верхняя лиана с белыми цветами",
        "indices": list(range(1, 9)),
        "layout": "horizontal",
        "visual_short": "зелёная лиана с белыми цветами",
        "alone_on_line": True,
        "width_risk": "high",
        "description": "Длинный бордюр: зелёная лиана с белыми цветами. Сегменты #001–#008 ставить подряд слева направо.",
        "description_emoji": "🌿🌸🍃✨",
        "tags": ["лиана", "бордюр", "цветы", "верх", "лес", "декор"],
        "mood": "cozy",
        "use_when": ["шапка сообщения", "рамка сверху", "лесная эстетика"],
    },
    {
        "id": "fairy_flying",
        "name": "Летящая фея",
        "indices": [9],
        "layout": "solo",
        "description": "Маленькая фея в полёте — самостоятельный акцент.",
        "description_emoji": "🧚✨🌿",
        "tags": ["фея", "магия", "лес", "акцент"],
        "mood": "wholesome",
        "use_when": ["сказочное настроение", "волшебство", "нежный декор"],
    },
    {
        "id": "mushroom_house",
        "name": "Грибной домик",
        "indices": [10],
        "layout": "solo",
        "description": "Миниатюрный грибной домик в лесу.",
        "description_emoji": "🍄🏠🌲",
        "tags": ["домик", "гриб", "сказка", "лес"],
        "mood": "wholesome",
        "use_when": ["уют", "сказочный лес", "cottagecore"],
    },
    {
        "id": "cottage_shell",
        "name": "Домик на ракушке",
        "indices": [11],
        "layout": "solo",
        "description": "Домик на изогнутой ракушке/корне — левый фрагмент сценки.",
        "description_emoji": "🏠🐚🌿",
        "tags": ["домик", "ракушка", "лес", "сказка"],
        "mood": "wholesome",
        "use_when": ["сказочная сценка", "лесной декор"],
    },
    {
        "id": "pink_flower_1",
        "name": "Розовый цветок",
        "indices": [12, 13],
        "layout": "horizontal",
        "description": "Розовый цветок: левая и правая половинки (#012 + #013).",
        "description_emoji": "🌸💗🌿",
        "tags": ["цветок", "розовый", "пара", "весна"],
        "mood": "wholesome",
        "use_when": ["нежный декор", "весеннее сообщение"],
    },
    {
        "id": "fairy_statue",
        "name": "Каменная фея-статуя",
        "indices": [14, 15],
        "layout": "horizontal",
        "description": "Статуя крылатой феи в камне — две половинки (#014 + #015).",
        "description_emoji": "🗿👼🌿",
        "tags": ["статуя", "фея", "камень", "сад"],
        "mood": "wholesome",
        "use_when": ["садовый декор", "сказочная сцена"],
    },
    {
        "id": "daisy_bouquet",
        "name": "Букет ромашек",
        "indices": [16],
        "layout": "solo",
        "description": "Белые ромашки с зелёными стеблями.",
        "description_emoji": "🌼🌿🤍",
        "tags": ["ромашки", "букет", "белый", "лето"],
        "mood": "wholesome",
        "use_when": ["лёгкое настроение", "лето", "нежность"],
    },
    {
        "id": "stem_segment_17",
        "name": "Сегмент стебля",
        "indices": [17],
        "layout": "solo",
        "description": "Вертикальный сегмент стебля/лианы — стыкуется с цветами сверху/снизу.",
        "description_emoji": "🌱🌿🪵",
        "tags": ["стебель", "лиана", "сегмент", "вертикаль"],
        "mood": "neutral",
        "use_when": ["собрать высокий цветок", "вертикальный декор"],
    },
    {
        "id": "mushroom_pair_1",
        "name": "Дикие грибы (пара 1)",
        "indices": [18, 19],
        "layout": "horizontal",
        "description": "Два гриба в лесной подстилке — половинки (#018 + #019).",
        "description_emoji": "🍄🌲🍂",
        "tags": ["грибы", "лес", "осень", "пара"],
        "mood": "wholesome",
        "use_when": ["лесная сцена", "осенний декор"],
    },
    {
        "id": "peach_poppy",
        "name": "Персиковый мак/анемон",
        "indices": [20, 21],
        "layout": "horizontal",
        "description": "Персиковый цветок с тёмным центром — фрагменты #020–#021.",
        "description_emoji": "🌸🍑🌿",
        "tags": ["цветок", "персиковый", "мак", "поле"],
        "mood": "wholesome",
        "use_when": ["цветочный декор", "нежная сцена"],
    },
    {
        "id": "forest_floor_22_26",
        "name": "Лесная подстилка и зелень",
        "indices": [22, 23, 24, 25, 26],
        "layout": "horizontal",
        "description": "Фрагменты мха, листвы и лесной земли — стыкуются в полосу.",
        "description_emoji": "🌿🍃🪨🌲",
        "tags": ["мох", "листва", "лес", "земля", "бордюр"],
        "mood": "neutral",
        "use_when": ["нижний бордюр", "лесной пол", "фон"],
    },
    {
        "id": "curly_vines",
        "name": "Завитые лианы",
        "indices": [27, 28, 29, 30],
        "layout": "horizontal",
        "description": "Изогнутые зелёные побеги — сегменты #027–#030 подряд.",
        "description_emoji": "🌿🍃〰️",
        "tags": ["лиана", "завиток", "зелень", "бордюр"],
        "mood": "wholesome",
        "use_when": ["рамка", "вьюнок", "лесной орнамент"],
    },
    _sparkle("sparkle_pink_35", 35, "Розовая звезда-блик", "✨💖⭐"),
    {
        "id": "red_anthurium",
        "name": "Красный антуриум",
        "indices": [38, 39],
        "layout": "horizontal",
        "description": "Красный антуриум — левая и правая половинки.",
        "description_emoji": "🌺❤️🌿",
        "tags": ["антуриум", "красный", "тропики", "цветок"],
        "mood": "love",
        "use_when": ["яркий акцент", "страсть", "тропический декор"],
    },
    {
        "id": "mushroom_house_2",
        "name": "Грибной домик 2",
        "indices": [45],
        "layout": "solo",
        "description": "Второй вариант лесного грибного домика.",
        "description_emoji": "🍄🏡🌲",
        "tags": ["домик", "гриб", "лес", "сказка"],
        "mood": "wholesome",
        "use_when": ["лесная сказка", "уют"],
    },
    {
        "id": "thorn_stems_46",
        "name": "Колючий стебель",
        "indices": [46],
        "layout": "solo",
        "description": "Тонкий колючий побег — стыкуется с другими стеблями.",
        "description_emoji": "🌿🥀🪵",
        "tags": ["стебель", "шипы", "ветка", "сегмент"],
        "mood": "neutral",
        "use_when": ["вертикальный декор", "дикая роза"],
    },
    _sparkle("sparkle_yellow_47", 47, "Жёлтая звезда-блик", "✨💛⭐"),
    {
        "id": "moth_wings",
        "name": "Крылья мотылька",
        "indices": [49, 50],
        "layout": "sandwich",
        "allows_text_between": True,
        "visual_short": "белые крылья мотылька",
        "description": "Большие белые крылья мотылька — слева #049, справа #050; между ними текст.",
        "description_emoji": "🦋🤍✨",
        "tags": ["крылья", "мотылёк", "рамка", "белый"],
        "mood": "magical",
        "use_when": ["обрамить сообщение", "нежная рамка"],
    },
    {
        "id": "mushroom_pair_2",
        "name": "Дикие грибы (пара 2)",
        "indices": [43, 44],
        "layout": "horizontal",
        "description": "Вторая пара лесных грибов (#043 + #044).",
        "description_emoji": "🍄🌲🍂",
        "tags": ["грибы", "лес", "пара"],
        "mood": "wholesome",
        "use_when": ["лесная сцена"],
    },
    {
        "id": "thorn_stems_row",
        "name": "Тонкие стебли и шипы",
        "indices": [53, 54, 57],
        "layout": "horizontal",
        "description": "Серия тонких стеблей, веток и шипов (#053–#057).",
        "description_emoji": "🌿🥀🪵",
        "tags": ["стебли", "шипы", "ветки", "бордюр"],
        "mood": "neutral",
        "use_when": ["вертикальный/горизонтальный декор", "дикий сад"],
    },
    {
        "id": "butterfly_wings_1",
        "name": "Крылья бабочки 1",
        "indices": [55, 56],
        "layout": "horizontal",
        "do_not_insert_text": True,
        "description": "Пара крыльев бабочки (#055 + #056) — стык без текста между половинками.",
        "description_emoji": "🦋✨🌿",
        "tags": ["крылья", "бабочка"],
        "mood": "wild",
        "use_when": ["лесной декор", "часть бордюра"],
    },
    {
        "id": "yellow_flower",
        "name": "Жёлто-оранжевый цветок",
        "indices": [61, 62],
        "layout": "horizontal",
        "description": "Крупный жёлто-оранжевый цветок — две половинки.",
        "description_emoji": "🌻🧡🌿",
        "tags": ["цветок", "жёлтый", "оранжевый", "крупный"],
        "mood": "happy",
        "use_when": ["солнечное настроение", "летний декор"],
    },
    {
        "id": "mushroom_pair_3",
        "name": "Дикие грибы (пара 3)",
        "indices": [63, 64],
        "layout": "horizontal",
        "description": "Третья пара грибов (#063 + #064).",
        "description_emoji": "🍄🌲🍂",
        "tags": ["грибы", "лес", "пара"],
        "mood": "wholesome",
        "use_when": ["лесная сцена"],
    },
    _sparkle("sparkle_green_75", 75, "Зелёная звезда-блик", "✨💚⭐"),
    {
        "id": "butterfly_wings_2",
        "name": "Крылья бабочки 2",
        "indices": [73, 74],
        "layout": "horizontal",
        "do_not_insert_text": True,
        "description": "Вторая пара крыльев бабочки (#073 + #074) — стык без текста.",
        "description_emoji": "🦋💫🌿",
        "tags": ["крылья", "бабочка"],
        "mood": "wild",
        "use_when": ["лесной декор"],
    },
    {
        "id": "orange_flower_2",
        "name": "Оранжевый цветок 2",
        "indices": [81, 82],
        "layout": "horizontal",
        "description": "Крупный оранжевый цветок — вторая вариация.",
        "description_emoji": "🌺🧡🍃",
        "tags": ["цветок", "оранжевый", "пара"],
        "mood": "happy",
        "use_when": ["яркий цветочный декор"],
    },
    {
        "id": "pink_blossom_1",
        "name": "Розовый цвет (пара 1)",
        "indices": [101, 102],
        "layout": "horizontal",
        "description": "Розовое цветение — половинки #101–#102.",
        "description_emoji": "🌸💗🌿",
        "tags": ["цветок", "розовый", "весна"],
        "mood": "wholesome",
        "use_when": ["нежный декор"],
    },
    {
        "id": "old_letters",
        "parent": "forest_table_scene",
        "name": "Старые письма",
        "indices": [105, 106],
        "layout": "horizontal",
        "complete": False,
        "description": "Пожелтевшие письма/свитки — часть сцены forest_table_scene.",
        "description_emoji": "📜✉️🌿",
        "tags": ["письмо", "свиток", "винтаж", "лес"],
        "mood": "nostalgic",
        "use_when": [],
    },
    {
        "id": "floral_teacup",
        "parent": "forest_table_scene",
        "name": "Чашка с цветами",
        "indices": [107, 108],
        "layout": "horizontal",
        "complete": False,
        "description": "Чайная чашка — часть сцены forest_table_scene.",
        "description_emoji": "☕🌸🍃",
        "tags": ["чай", "чашка", "цветы", "уют"],
        "mood": "cozy",
        "use_when": [],
    },
    {
        "id": "fairy_deer",
        "parent": "forest_table_scene",
        "name": "Фея на оленёнке",
        "indices": [109, 110],
        "layout": "horizontal",
        "complete": False,
        "description": "Фея с оленёнком — часть сцены forest_table_scene.",
        "description_emoji": "🧚🦌✨",
        "tags": ["фея", "олень", "сказка", "лес"],
        "mood": "magical",
        "use_when": [],
    },
    {
        "id": "mushroom_house_3",
        "name": "Грибной домик 3",
        "indices": [111],
        "layout": "solo",
        "description": "Третий вариант грибного домика.",
        "description_emoji": "🍄🏠🌲",
        "tags": ["домик", "гриб", "лес"],
        "mood": "wholesome",
        "use_when": ["сказочный лес"],
    },
    _sparkle("sparkle_pink_112", 112, "Розовый блик 2", "✨💖⭐"),
    {
        "id": "green_anthurium",
        "name": "Зелёный антуриум",
        "indices": [115, 116],
        "layout": "horizontal",
        "description": "Зелёный листоцветок-антуриум.",
        "description_emoji": "🌿💚🌺",
        "tags": ["антуриум", "зелёный", "лист", "цветок"],
        "mood": "wholesome",
        "use_when": ["зелёный декор", "тропики"],
    },
    {
        "id": "pink_blossom_2",
        "name": "Розовый цвет (пара 2)",
        "indices": [121, 122],
        "layout": "horizontal",
        "description": "Розовые цветы — вторая пара.",
        "description_emoji": "🌸💗✨",
        "tags": ["цветок", "розовый"],
        "mood": "wholesome",
        "use_when": ["весенний декор"],
    },
    _sparkle("sparkle_yellow_96", 96, "Жёлтый блик 2", "✨💛⭐"),
    {
        "id": "white_blossom",
        "name": "Белый цвет",
        "indices": [137, 138],
        "layout": "horizontal",
        "description": "Белое цветение — пара половинок.",
        "description_emoji": "🤍🌸🌿",
        "tags": ["цветок", "белый", "нежный"],
        "mood": "wholesome",
        "use_when": ["свадебный декор", "чистота"],
    },
    {
        "id": "willow_leaves",
        "name": "Ивовые листья",
        "indices": [141, 142],
        "layout": "horizontal",
        "description": "Свисающие ивовые ветви — два сегмента.",
        "description_emoji": "🌿🍃💚",
        "tags": ["ива", "листва", "ветви", "зелень"],
        "mood": "wholesome",
        "use_when": ["верхний бордюр", "плакучая ива"],
    },
    {
        "id": "pink_cluster",
        "name": "Кластер розовых цветов",
        "indices": [149, 150],
        "layout": "horizontal",
        "description": "Плотная группа мелких розовых цветов.",
        "description_emoji": "🌸🌸💗",
        "tags": ["цветы", "розовый", "кластер", "куст"],
        "mood": "love",
        "use_when": ["романтичный декор", "цветущий куст"],
    },
    {
        "id": "fairy_flower_hat",
        "name": "Фея в цветочной шляпке",
        "indices": [155, 156],
        "layout": "horizontal",
        "description": "Девочка-фея в шляпке из цветка.",
        "description_emoji": "🧚🌸👒",
        "tags": ["фея", "цветок", "шляпка", "девочка"],
        "mood": "wholesome",
        "use_when": ["сказка", "милота"],
    },
    {
        "id": "bonsai",
        "name": "Бонсай",
        "layout": "grid",
        "rows": [[157, 158], [165]],
        "visual_short": "бонсай: крона + горшок",
        "description": "Бонсай 2×2: верх #157+#158 (крона), низ #165 (горшок); между строками перевод строки.",
        "description_emoji": "🪴🌳✨",
        "tags": ["бонсай", "дерево", "горшок", "сад"],
        "mood": "cozy",
        "use_when": ["спокойствие", "минимализм", "сад"],
        "do_not_mix_with": ["clover_full", "heart_apple_row"],
    },
    {
        "id": "mossy_trunk",
        "name": "Мшистый ствол",
        "indices": [161, 162],
        "layout": "horizontal",
        "description": "Толстый ствол дерева с мхом.",
        "description_emoji": "🌳🪨🍃",
        "tags": ["ствол", "мох", "дерево", "лес"],
        "mood": "neutral",
        "use_when": ["лесной фон", "основание сцены"],
    },
    {
        "id": "child_in_flowers",
        "name": "Куколка в цветах",
        "indices": [163, 164],
        "layout": "stack",
        "order": [163, 164],
        "description": "Фигурка в цветочном наряде: верх #163 (лицо/плечи), низ #164 (юбка из лепестков) — столбиком через \\n.",
        "description_emoji": "👧🌸🌿",
        "tags": ["куколка", "цветы", "вертикаль", "стек"],
        "mood": "wholesome",
        "use_when": ["милота", "весна", "сказка"],
    },
    {
        "id": "heart_apple_row",
        "name": "Яблоки с сердцем (верхний ряд)",
        "indices": [181, 182],
        "layout": "horizontal",
        "complete": True,
        "description": "Два яблока с сердцевидным узором — только верхний ряд #181+#182; не смешивать с клевером.",
        "description_emoji": "🍎❤️✨",
        "tags": ["яблоко", "сердце", "любовь", "горизонталь"],
        "mood": "love",
        "use_when": ["романтика", "сказочный намёк"],
        "do_not_mix_with": ["clover_full", "clover_row_top", "clover_row_bottom"],
    },
    {
        "id": "butterfly_wings_3",
        "name": "Крылья бабочки 3",
        "indices": [189, 190],
        "layout": "horizontal",
        "do_not_insert_text": True,
        "description": "Третья пара крыльев бабочки (#189 + #190) — стык без текста.",
        "description_emoji": "🦋✨🤍",
        "tags": ["крылья", "бабочка"],
        "mood": "wild",
        "use_when": ["лесной декор"],
    },
    {
        "id": "flower_pot",
        "name": "Горшок для цветов",
        "indices": [193],
        "layout": "solo",
        "description": "Терракотовый цветочный горшок — основание для сборки растения.",
        "description_emoji": "🪴🏺🌿",
        "tags": ["горшок", "глиняный", "основание", "сад"],
        "mood": "neutral",
        "use_when": ["поставить цветок сверху", "садовый декор"],
    },
    {
        "id": "thorn_border",
        "name": "Нижний бордюр стеблей",
        "indices": [194, 195, 196, 197, 198],
        "layout": "horizontal",
        "description": "Тонкие стебли и ветви для нижнего бордюра (#194–#198).",
        "description_emoji": "🌿🥀🪵",
        "tags": ["стебли", "бордюр", "низ", "лес"],
        "mood": "neutral",
        "use_when": ["нижняя рамка сообщения"],
    },
    _sparkle("sparkle_pink_199", 199, "Розовый блик 4", "✨💖⭐"),
    {
        "id": "forest_accent_200",
        "name": "Лесной акцент",
        "indices": [200],
        "layout": "solo",
        "description": "Завершающий лесной декоративный элемент пака.",
        "description_emoji": "🌲✨🌿",
        "tags": ["лес", "акцент", "финал"],
        "mood": "wholesome",
        "use_when": ["завершить композицию"],
    },
]

# Родительские grid/stack и неполные части
PARENT_COMBOS: list[dict] = [
    {
        "id": "forest_table_scene",
        "name": "Лесной столик",
        "layout": "grid",
        "rows": [[105, 106], [107, 108], [109, 110]],
        "parts": ["old_letters", "floral_teacup", "fairy_deer"],
        "complete": True,
        "visual_short": "письма, чашка, фея на олене",
        "description": "Сцена чаепития: письма #105–#106, чашка #107–#108, фея на олене #109–#110.",
        "description_emoji": "📜☕🧚🦌",
        "tags": ["чай", "фея", "олень", "письмо", "сцена"],
        "mood": "cozy",
        "use_when": ["чаепитие в лесу", "сказочная сцена"],
    },
    {
        "id": "deep_forest_panorama",
        "name": "Глубинный лес",
        "layout": "grid",
        "rows": [[166, 167, 168, 169, 170, 171, 172, 173, 174], [175, 176, 177, 178]],
        "complete": True,
        "visual_short": "тёмный мох + фиолетовые бутоны",
        "description": "Панорама глубинного леса: верхний ряд #166–#174, нижний #175–#178; не включать #165 (горшок бонсая).",
        "description_emoji": "🌲🌿💜",
        "tags": ["лес", "мох", "бутоны", "глубина", "панорама"],
        "mood": "wild",
        "use_when": ["лесной фон", "атмосферная сцена"],
        "alone_on_line": True,
        "width_risk": "high",
    },
    {
        "id": "clover_full",
        "name": "Четырёхлистный клевер",
        "layout": "grid",
        "rows": [[179, 180], [187, 188]],
        "parts": ["clover_row_top", "clover_row_bottom"],
        "complete": True,
        "description": "Клевер 2×2: строка1 #179+#180, строка2 #187+#188; между строками перевод строки.",
        "description_emoji": "🍀💚✨",
        "tags": ["клевер", "удача", "сетка", "2x2"],
        "mood": "happy",
        "use_when": ["удача", "весна", "талисман"],
        "do_not_mix_with": ["heart_apple_row"],
    },
    {
        "id": "clover_row_top",
        "parent": "clover_full",
        "name": "Клевер — верхний ряд",
        "indices": [179, 180],
        "layout": "horizontal",
        "complete": False,
        "description": "Неполный фрагмент: только верх клевера. Используй clover_full.",
        "description_emoji": "🍀💚",
        "tags": ["клевер", "верх", "часть"],
        "mood": "happy",
        "use_when": [],
    },
    {
        "id": "clover_row_bottom",
        "parent": "clover_full",
        "name": "Клевер — нижний ряд",
        "indices": [187, 188],
        "layout": "horizontal",
        "complete": False,
        "description": "Неполный фрагмент: только низ клевера. Используй clover_full.",
        "description_emoji": "🍀💚",
        "tags": ["клевер", "низ", "часть"],
        "mood": "happy",
        "use_when": [],
    },
    _sparkle("sparkle_pink_186", 186, "Розовый блик 3", "✨💖⭐"),
    _spacer(191),
    _spacer(192),
]

# Дополнительные пары/группы для непокрытых индексов (по рядам сетки)
EXTRA_GROUPS: list[dict] = [
    {"id": "green_leaves_31_34", "indices": [31, 32, 33, 34], "name": "Зелёная листва и деревце", "emoji": "🌿🌳🍃", "tags": ["листва", "дерево", "зелень"]},
    {"id": "forest_greenery_36_37", "indices": [36, 37], "name": "Лесная зелень", "emoji": "🌲🍃🌿", "tags": ["лес", "зелень"]},
    {"id": "floral_40_42", "indices": [40, 41, 42], "name": "Лесные цветы и листва", "emoji": "🌸🌿🍃", "tags": ["цветы", "листва"]},
    {"id": "petals_48", "indices": [48], "name": "Лепесток-акцент", "emoji": "🌸✨", "tags": ["лепесток", "акцент"], "solo": True},
    {"id": "peaceful_51", "indices": [51], "name": "Спокойное лицо в листве", "emoji": "😌🌿", "tags": ["спокойствие", "листва"], "solo": True},
    {"id": "blur_vibrate_52_58", "indices": [52, 58], "name": "Размытые листовые фрагменты", "emoji": "🌿💫🍃", "tags": ["листва", "движение"]},
    {"id": "tongue_59", "indices": [59], "name": "Ягодный/цветочный акцент", "emoji": "🌸🍃", "tags": ["акцент", "природа"], "solo": True},
    {"id": "cry_60", "indices": [60], "name": "Роса/капли на листе", "emoji": "💧🌿", "tags": ["роса", "лист"], "solo": True},
    {"id": "flowers_65_72", "indices": [65, 66, 67, 68, 69, 70, 71, 72], "name": "Лесные бутоны и листва", "emoji": "🌸🌿🍃", "tags": ["бутоны", "листва", "лес"]},
    {"id": "distress_75_77", "indices": [76, 77], "name": "Лесные ветви-акценты", "emoji": "🌿🪵", "tags": ["ветви"]},
    {"id": "blank_78", "indices": [78], "name": "Светлый листовой фон", "emoji": "🍃✨", "tags": ["фон", "лист"], "solo": True},
    {"id": "tongue_79_80", "indices": [79, 80], "name": "Подсолнух и зелень", "emoji": "🌻🌿", "tags": ["подсолнух", "лето"]},
    {"id": "flowers_83_95", "indices": [83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], "name": "Лесные цветы и персонажи", "emoji": "🌸🧚🌿", "tags": ["цветы", "лес", "сказка"]},
    {"id": "forest_greenery_97_100", "indices": [97, 98, 99, 100], "name": "Лесная зелень и бутоны", "emoji": "🌿🌸🍃", "tags": ["зелень", "бутоны", "лес"]},
    {"id": "sparkle_132", "indices": [132], "name": "Зелёный блик", "emoji": "✨💚", "tags": ["блик"], "solo": True, "sparkle": True},
    {"id": "flowers_103_104", "indices": [103, 104], "name": "Белые бутоны", "emoji": "🤍🌸", "tags": ["бутоны", "белый"]},
    {"id": "flowers_113_114", "indices": [113, 114], "name": "Розовые лепестки", "emoji": "🌸💗", "tags": ["лепестки"]},
    {"id": "flowers_117_120", "indices": [117, 118, 119, 120], "name": "Весенние бутоны", "emoji": "🌸🌿", "tags": ["бутоны", "весна"]},
    {"id": "flowers_123_131", "indices": [123, 124, 125, 126, 127, 128, 129, 130, 131], "name": "Лесная поляна", "emoji": "🌿🌸🍃", "tags": ["поляна", "цветы"]},
    {"id": "flowers_133_136", "indices": [133, 134, 135, 136], "name": "Луговые цветы", "emoji": "🌼🌿", "tags": ["луг", "цветы"]},
    {"id": "flowers_139_140", "indices": [139, 140], "name": "Веточки с бутонами", "emoji": "🌿🌸", "tags": ["веточки"]},
    {"id": "flowers_143_148", "indices": [143, 144, 145, 146, 147, 148], "name": "Цветущие ветви", "emoji": "🌸🌿", "tags": ["ветви", "цветы"]},
    {"id": "flowers_151_154", "indices": [151, 152, 153, 154], "name": "Лесные бутоны 2", "emoji": "🌿🌸", "tags": ["бутоны"]},
    {"id": "flowers_159_160", "indices": [159, 160], "name": "Мховые камни", "emoji": "🪨🍃", "tags": ["мох", "камни"]},
    {"id": "flowers_183_185", "indices": [183, 184, 185], "name": "Лесные ягоды и листва", "emoji": "🫐🌿", "tags": ["ягоды", "листва"]},
]


def build_extra_combos() -> list[dict]:
    combos = []
    for g in EXTRA_GROUPS:
        if not g.get("indices") or g["id"].startswith("broken") or g.get("skip"):
            continue
        if g.get("sparkle"):
            combos.append(_sparkle(g["id"], g["indices"][0], g["name"], g["emoji"]))
            continue
        layout = "solo" if g.get("solo") or len(g["indices"]) == 1 else "horizontal"
        combos.append(
            {
                "id": g["id"],
                "name": g["name"],
                "indices": g["indices"],
                "layout": layout,
                "description": f"{g['name']} — фрагменты {', '.join(f'#{i:03d}' for i in g['indices'])}.",
                "description_emoji": g["emoji"],
                "tags": g["tags"] + ["природа", "лес", "фрагмент"],
                "mood": "wholesome",
                "use_when": ["лесной декор", "собрать сцену", "cottagecore"],
            }
        )
    return combos


SCENES = [
    {
        "id": "morning_path",
        "blocks": ["vine_border_top", "bonsai", "thorn_border"],
        "between_blocks": "blank_line",
        "description": "Доброе утро: шапка-лиана, бонсай, нижний бордюр",
    },
    {
        "id": "forest_tea",
        "blocks": ["vine_border_top", "forest_table_scene", "thorn_border"],
        "between_blocks": "blank_line",
        "description": "Чаепитие в лесу: лиана, столик с чашкой и феей, бордюр",
    },
    {
        "id": "text_frame",
        "blocks": ["moth_wings", "spacer_191"],
        "between_blocks": "blank_line",
        "description": "Рамка с текстом между крыльями мотылька",
    },
]


def build_items_and_combos(count: int = 200) -> tuple[list[dict], list[dict]]:
    raw = COMBOS_RAW + PARENT_COMBOS + build_extra_combos()
    return build_items(count, raw, theme="лесная тропа", pack_type="composite")


def main() -> None:
    items, combos = build_items_and_combos(200)
    spacer_combos = [c for c in combos if c.get("layout") == "spacer"]
    data = {
        "pack": PACK,
        "pack_type": "composite",
        "agent_rules": AGENT_RULES,
        "spacer_guide": SPACER_GUIDANCE,
        "scenes": SCENES,
        "spacers": [
            {
                "id": c["id"],
                "index": c["indices"][0],
                "layout": "spacer",
                "render": c.get("render", "padding"),
                "max_per_message": c.get("max_per_message", 8),
                "description": c.get("description", ""),
                "use_when": c.get("use_when", []),
            }
            for c in spacer_combos
        ],
        "items": items,
        "combos": combos,
        "by_tag": build_by_tag(items, combos, pack_type="composite"),
    }
    out = Path("output") / PACK / "labels_by_index.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    covered = sum(1 for i in items if i.get("combo_group"))
    print(f"Wrote {out}: {len(items)} items, {len(combos)} combos, covered={covered}")


if __name__ == "__main__":
    main()
